/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Eventstream20 {
  path: string;
  event: "create" | "update" | "delete" | "direct" | "extsync" | "console" | "ready";
  data?: {
    [k: string]: unknown;
  };
  meta_object: {
    id?: string;
    type: string;
    version: string;
    owner?: string;
  };
  timestamp?: string;
  meta: Meta21;
}
export interface Meta21 {
  id?: string;
  type?: string;
  version?: string;
  manufacturer?: (string | ("unassigned" | "admin")) & string;
  owner?: (string | ("unassigned" | "admin")) & string;
  created?: (string | "not_available") & string;
  updated?: (string | "not_available") & string;
  application?: string;
  installation?: string;
  revision?: number;
  trace?: string;
  oem?: string;
  deprecated?: boolean;
  redirect?: string;
  size?: number;
  path?: string;
  parent?: string;
  error?: {
    [k: string]: unknown;
  };
  icon?: string;
  tag?: string[];
  tag_by_user?: string[];
  name_by_user?: string;
  warning?: {
    message?: string;
    data?: {
      [k: string]: unknown;
    };
    code?: number;
    [k: string]: unknown;
  }[];
  parent_name?: {
    [k: string]: unknown;
  };
  read_only?: boolean;
  original_id?: string;
  alert?: string[];
}
