name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x', '18.x']
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Installing
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Linting
        uses: borales/actions-yarn@v4
        with:
          cmd: lint

      - name: Testing
        uses: borales/actions-yarn@v4
        with:
          cmd: test
